dist: trusty
sudo: true

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo add-apt-repository ppa:fkrull/deadsnakes
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python3.5 python3.5-dev

language:
  - c
  - cpp

compiler:
  - clang
  - gcc

script:
  - qmake -makefile -o Makefile "CONFIG+= travis release " cpyjava.pro
  - make
