dist: trusty
sudo: true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sf5fN/+VX/GmZYHGb9WhQ/O5XaU/9N0Wk9tdZUcCkzqKyq7Ym6R+tg82RCeCjU/zw7ORXfc3SDfC9R3Jpz2fcpCTSUYyB2jBoc0gT5C2r+nIdrFOEY9cLBVrH7Gk9MrB3hcuFZNC4VrZPVxrLrdYHPZwbya85GebrNyYgV2YfLuRre6kj6cDOnJv2CRmXQuhspeCbYJLyCXdHgnlYojKMZjPN3RHnwLK/haRUQJUR6eVhg65Sphe84UaiVyppthfJZzCt1e8nVLQaLy1pxRq8dZtPnT1f3+sdkHw385bvO8uRJarU2FudkfmTFrGveOVF++F7tsHB8s53FBr1z5B4dQeATEul1j4lMvk1Dz5JpYLJcVWVuZORjfeqhRWqswgAzzMuDgn5w3ECM+eCBhxmtw3t4Y+zSI8PEqy0LkPIxYdBUGW+v3/UpITsPV2dRfZs9tYOpdaVQp+QNBa8A60jKQce4VVMY2/A3Of6br1jDH1l435slTpx3Htc2jt9ssY9kGg90iN8/XCl6W/JrVa16/mgTZEiUZYUOWFiaQazLifdQWpjuYLBx8nrwtqV8MW0xgMf/pJvHasi7W8LWbitCrolKtJBE1DNzoPGquxgkSj3uytem3F9qJo/CilC6XMbuxMqPdGktlaSpArL4yTKVSaSYXoms6OxARqNHb+4WM="

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo add-apt-repository --yes ppa:fkrull/deadsnakes
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3.5 python3.5-dev
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

language:
  - c
  - cpp

compiler:
  - clang
  - gcc

script:
  - qmake -makefile -o Makefile "CONFIG+= travis release " cpyjava.pro
  - make

branches:
  only:
  - master
  - coverity_scan

addons:
  coverity_scan:
    project:
      name: "m-g-90/cpyjava"
      description: ""
    notification_email: "29159709+m-g-90@users.noreply.github.com"
    build_command_prepend: "qmake -makefile -o Makefile \"CONFIG+= travis release \" cpyjava.pro"
    build_command: make
    branch_pattern: coverity_scan
