codecov:
  ci:
    - "!icicleci.com"
  branch: master
    
coverage:
  precision: 4         
  round: down          
  range: 10...100
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 0%
        branches: master
        if_ci_failed: error
